### ISSUE TITLE
Error installing on Ubuntu server 20.04 LTS

### ISSUE THREAD

**Issue by noisypacket** [YoRyan/smtp-translator#2]
go version go1.16.7 linux/amd64

Details:
go: downloading github.com/YoRyan/smtp-translator v0.0.0-20210607023058-5481e2040acf
go: downloading github.com/gregdel/pushover v0.0.0-20200820121613-505cfd60a340
go: downloading github.com/mhale/smtpd v0.0.0-20200509114310-d7a07f752336
go: downloading github.com/gregdel/pushover v1.1.0
go: downloading github.com/mhale/smtpd v0.8.0
# github.com/YoRyan/smtp-translator
go/pkg/mod/github.com/!yo!ryan/smtp-translator@v0.0.0-20210607023058-5481e2040acf/main.go:190:3: cannot use func literal (type func(net.Addr, string, []string, []byte)) as type smtpd.Handler in field value

**Comment by YoRyan** [comment]
Ubuntu Focal includes Go 1.13.8, not 1.16. That's too old for some of the syntax I used.

I would suggest upgrading your Go version, upgrading to Ubuntu Jammy, or using the Docker image.
